const num1 = 31
const num2 = 2
const multiply = num1 * num2
const min = 1;
const maxValue = 10
const random = Math.floor(Math.random() * (maxValue - min + 1)) + min
const num3 = 12
const num4 = 3
const mod = num3 / num4
const max = Math.max(18,19,20)
